/** Short page descriptions keyed by route (used to build app-sitemap.json). */
export const PAGE_BLURBS: Record<string, string> = {
  "/admin":
    "Home dashboard: KPIs, charts, alerts across sales, inventory, and finance.",
  "/admin/products":
    "Product catalog: SKUs, variants, pricing; New item opens the create modal.",
  "/admin/categories": "Product category taxonomy.",
  "/admin/brands": "Brand master list.",
  "/admin/item-units": "Units of measure for items.",
  "/admin/inventory":
    "Online store stock by variant; transfers and availability for BuyHub.",
  "/admin/erp/store-inventory": "Store on-hand stock, WAC, purchase and sales history per product.",
  "/admin/erp/stock-details": "Redirects to Store inventory.",
  "/admin/erp/stock-adjustments": "Correct on-hand quantities.",
  "/admin/erp/item-transactions": "Stock movement audit trail.",
  "/admin/erp/store-transfers": "Move stock between stores.",
  "/admin/erp/transfer-requests": "Request stock from another store.",
  "/admin/erp/transfer-approvals": "Approve pending transfer requests.",
  "/admin/erp/transfer-statement": "Transfer history and statement.",
  "/admin/erp/transfer-bulk-payments": "Bulk payments linked to transfers.",
  "/admin/erp/stores": "Store/branch locations.",
  "/admin/customers": "Customer accounts and contacts.",
  "/admin/orders": "E-commerce orders from BuyHub.",
  "/admin/erp/fulfillment-queue": "Assign orders to stores for fulfillment.",
  "/admin/billing": "POS counter checkout and retail billing.",
  "/admin/erp/estimates": "Quotes and proposals before invoicing.",
  "/admin/erp/sales-orders": "Committed sales orders and fulfillment.",
  "/admin/erp/invoices": "Tax invoices and AR billing.",
  "/admin/erp/credit-notes": "Customer credits and returns.",
  "/admin/erp/payments": "Customer payments received (AR).",
  "/admin/erp/customer-bulk-payments": "Batch customer payment entry.",
  "/admin/erp/recurring-invoices": "Subscription-style repeating invoices.",
  "/admin/vendors": "Supplier/vendor master.",
  "/admin/purchase-orders": "POs to vendors.",
  "/admin/erp/purchase-bills": "Vendor bills and GRN-style purchase entry.",
  "/admin/erp/vendor-credits": "Supplier credit notes.",
  "/admin/erp/expenses": "Operating expenses and petty cash.",
  "/admin/erp/recurring-bills": "Repeating vendor bills.",
  "/admin/erp/landed-costs": "Freight, duty, and landed cost allocation.",
  "/admin/erp/supplier-payments": "Payments made to vendors (AP).",
  "/admin/erp/supplier-bulk-payments": "Batch vendor payments.",
  "/admin/erp/banking": "Cash and bank accounts.",
  "/admin/erp/payment-statement": "Cash book / payment statement.",
  "/admin/erp/profit-withdrawals": "Owner profit withdrawals.",
  "/admin/erp/account-types": "Ledger account type setup.",
  "/admin/erp/accounts": "Chart of accounts (GL).",
  "/admin/erp/journal-entries": "Manual journal entries.",
  "/admin/erp/reports": "Financial and operational reports.",
  "/admin/erp/financial-summary": "Finance KPI summary.",
  "/admin/erp/reconciliation": "Stock and account reconciliation.",
  "/admin/finance": "Online store analytics and margins.",
  "/admin/erp/vat-returns": "VAT return filing workspace.",
  "/admin/erp/vat-payments": "VAT tax payments.",
  "/admin/erp/employees": "Employee records (HR).",
  "/admin/erp/pay-slips": "Employee pay slips.",
  "/admin/erp/salary-payments": "Salary payment runs.",
  "/admin/erp/salary-bulk-payments": "Bulk salary payments.",
  "/admin/erp/employee-opening-balances": "Employee opening balances.",
  "/admin/erp/fixed-assets": "Fixed assets and depreciation.",
  "/admin/business": "Business settings: currency, region, store config.",
  "/admin/config/tax": "Tax rate configuration.",
  "/admin/config/push": "Push notification campaigns.",
  "/admin/users": "Team users and roles.",
  "/admin/config": "Account profile and security settings.",
};

export function defaultPageBlurb(section: string, name: string): string {
  return `${section}: ${name}.`;
}
